
import { Item } from '../types';

export const ITEMS: Item[] = [
  // Armor
  { id: 'padded', name: 'Стеганый доспех', type: 'armor', cost: 5, ac: 11, weight: 8, properties: ['Помеха на скрытность'], source: 'dnd.su' },
  { id: 'leather', name: 'Кожаный доспех', type: 'armor', cost: 10, ac: 11, weight: 10, source: 'dnd.su' },
  { id: 'studded', name: 'Проклепанный кожаный', type: 'armor', cost: 45, ac: 12, weight: 13, source: 'dnd.su' },
  { id: 'hide', name: 'Шкурный доспех', type: 'armor', cost: 10, ac: 12, weight: 12, source: 'dnd.su' },
  { id: 'chain_shirt', name: 'Кольчужная рубаха', type: 'armor', cost: 50, ac: 13, weight: 20, source: 'dnd.su' },
  { id: 'scale_mail', name: 'Чешуйчатый доспех', type: 'armor', cost: 50, ac: 14, weight: 45, properties: ['Помеха на скрытность'], source: 'dnd.su' },
  { id: 'breastplate', name: 'Кираса', type: 'armor', cost: 400, ac: 14, weight: 20, source: 'dnd.su' },
  { id: 'half_plate', name: 'Полулаты', type: 'armor', cost: 750, ac: 15, weight: 40, properties: ['Помеха на скрытность'], source: 'dnd.su' },
  { id: 'ring_mail', name: 'Колечный доспех', type: 'armor', cost: 30, ac: 14, weight: 40, properties: ['Помеха на скрытность'], source: 'dnd.su' },
  { id: 'chain_mail', name: 'Кольчуга', type: 'armor', cost: 75, ac: 16, weight: 55, properties: ['Помеха на скрытность', 'Сил 13'], source: 'dnd.su' },
  { id: 'splint', name: 'Наборный доспех', type: 'armor', cost: 200, ac: 17, weight: 60, properties: ['Помеха на скрытность', 'Сил 15'], source: 'dnd.su' },
  { id: 'plate', name: 'Латы', type: 'armor', cost: 1500, ac: 18, weight: 65, properties: ['Помеха на скрытность', 'Сил 15'], source: 'dnd.su' },
  { id: 'shield', name: 'Щит', type: 'armor', cost: 10, ac: 2, weight: 6, source: 'dnd.su' },

  // Weapons
  { id: 'club', name: 'Дубинка', type: 'weapon', cost: 0.1, damage: '1d4 дробящий', weight: 2, properties: ['Легкое'], source: 'dnd.su' },
  { id: 'dagger', name: 'Кинжал', type: 'weapon', cost: 2, damage: '1d4 колющий', weight: 1, properties: ['Легкое', 'Метательное (20/60)', 'Фехтовальное'], source: 'dnd.su' },
  { id: 'greatclub', name: 'Дубина', type: 'weapon', cost: 0.2, damage: '1d8 дробящий', weight: 10, properties: ['Двуручное'], source: 'dnd.su' },
  { id: 'handaxe', name: 'Ручной топор', type: 'weapon', cost: 5, damage: '1d6 рубящий', weight: 2, properties: ['Легкое', 'Метательное (20/60)'], source: 'dnd.su' },
  { id: 'javelin', name: 'Метательное копье', type: 'weapon', cost: 0.5, damage: '1d6 колющий', weight: 2, properties: ['Метательное (30/120)'], source: 'dnd.su' },
  { id: 'light_hammer', name: 'Легкий молот', type: 'weapon', cost: 2, damage: '1d4 дробящий', weight: 2, properties: ['Легкое', 'Метательное (20/60)'], source: 'dnd.su' },
  { id: 'mace', name: 'Булава', type: 'weapon', cost: 5, damage: '1d6 дробящий', weight: 4, source: 'dnd.su' },
  { id: 'quarterstaff', name: 'Боевой посох', type: 'weapon', cost: 0.2, damage: '1d6 дробящий', weight: 4, properties: ['Универсальное (1d8)'], source: 'dnd.su' },
  { id: 'sickle', name: 'Серп', type: 'weapon', cost: 1, damage: '1d4 рубящий', weight: 2, properties: ['Легкое'], source: 'dnd.su' },
  { id: 'spear', name: 'Копье', type: 'weapon', cost: 1, damage: '1d6 колющий', weight: 3, properties: ['Метательное (20/60)', 'Универсальное (1d8)'], source: 'dnd.su' },
  { id: 'crossbow_light', name: 'Арбалет, легкий', type: 'weapon', cost: 25, damage: '1d8 колющий', weight: 5, properties: ['Боеприпас (80/320)', 'Двуручное'], source: 'dnd.su' },
  { id: 'dart', name: 'Дротик', type: 'weapon', cost: 0.05, damage: '1d4 колющий', weight: 0.25, properties: ['Фехтовальное', 'Метательное (20/60)'], source: 'dnd.su' },
  { id: 'shortbow', name: 'Короткий лук', type: 'weapon', cost: 25, damage: '1d6 колющий', weight: 2, properties: ['Боеприпас (80/320)', 'Двуручное'], source: 'dnd.su' },
  { id: 'sling', name: 'Праща', type: 'weapon', cost: 0.1, damage: '1d4 дробящий', weight: 0, properties: ['Боеприпас (30/120)'], source: 'dnd.su' },
  
  { id: 'battleaxe', name: 'Боевой топор', type: 'weapon', cost: 10, damage: '1d8 рубящий', weight: 4, properties: ['Универсальное (1d10)'], source: 'dnd.su' },
  { id: 'flail', name: 'Цеп', type: 'weapon', cost: 10, damage: '1d8 дробящий', weight: 2, source: 'dnd.su' },
  { id: 'glaive', name: 'Глефа', type: 'weapon', cost: 20, damage: '1d10 рубящий', weight: 6, properties: ['Двуручное', 'Досягаемость', 'Тяжелое'], source: 'dnd.su' },
  { id: 'greataxe', name: 'Секира', type: 'weapon', cost: 30, damage: '1d12 рубящий', weight: 7, properties: ['Двуручное', 'Тяжелое'], source: 'dnd.su' },
  { id: 'greatsword', name: 'Двуручный меч', type: 'weapon', cost: 50, damage: '2d6 рубящий', weight: 6, properties: ['Двуручное', 'Тяжелое'], source: 'dnd.su' },
  { id: 'halberd', name: 'Алебарда', type: 'weapon', cost: 20, damage: '1d10 рубящий', weight: 6, properties: ['Двуручное', 'Досягаемость', 'Тяжелое'], source: 'dnd.su' },
  { id: 'lance', name: 'Длинное копье', type: 'weapon', cost: 10, damage: '1d12 колющий', weight: 6, properties: ['Досягаемость', 'Особое'], source: 'dnd.su' },
  { id: 'longsword', name: 'Длинный меч', type: 'weapon', cost: 15, damage: '1d8 рубящий', weight: 3, properties: ['Универсальное (1d10)'], source: 'dnd.su' },
  { id: 'maul', name: 'Молот', type: 'weapon', cost: 10, damage: '2d6 дробящий', weight: 10, properties: ['Двуручное', 'Тяжелое'], source: 'dnd.su' },
  { id: 'morningstar', name: 'Моргенштерн', type: 'weapon', cost: 15, damage: '1d8 колющий', weight: 4, source: 'dnd.su' },
  { id: 'pike', name: 'Пика', type: 'weapon', cost: 5, damage: '1d10 колющий', weight: 18, properties: ['Двуручное', 'Досягаемость', 'Тяжелое'], source: 'dnd.su' },
  { id: 'rapier', name: 'Рапира', type: 'weapon', cost: 25, damage: '1d8 колющий', weight: 2, properties: ['Фехтовальное'], source: 'dnd.su' },
  { id: 'scimitar', name: 'Скимитар', type: 'weapon', cost: 25, damage: '1d6 рубящий', weight: 3, properties: ['Легкое', 'Фехтовальное'], source: 'dnd.su' },
  { id: 'shortsword', name: 'Короткий меч', type: 'weapon', cost: 10, damage: '1d6 колющий', weight: 2, properties: ['Легкое', 'Фехтовальное'], source: 'dnd.su' },
  { id: 'trident', name: 'Трезубец', type: 'weapon', cost: 5, damage: '1d6 колющий', weight: 4, properties: ['Метательное (20/60)', 'Универсальное (1d8)'], source: 'dnd.su' },
  { id: 'war_pick', name: 'Боевая кирка', type: 'weapon', cost: 5, damage: '1d8 колющий', weight: 2, source: 'dnd.su' },
  { id: 'warhammer', name: 'Боевой молот', type: 'weapon', cost: 15, damage: '1d8 дробящий', weight: 2, properties: ['Универсальное (1d10)'], source: 'dnd.su' },
  { id: 'whip', name: 'Кнут', type: 'weapon', cost: 2, damage: '1d4 рубящий', weight: 3, properties: ['Досягаемость', 'Фехтовальное'], source: 'dnd.su' },
  { id: 'blowgun', name: 'Духовая трубка', type: 'weapon', cost: 10, damage: '1 колющий', weight: 1, properties: ['Боеприпас (25/100)'], source: 'dnd.su' },
  { id: 'crossbow_hand', name: 'Арбалет, ручной', type: 'weapon', cost: 75, damage: '1d6 колющий', weight: 3, properties: ['Боеприпас (30/120)', 'Легкое'], source: 'dnd.su' },
  { id: 'crossbow_heavy', name: 'Арбалет, тяжелый', type: 'weapon', cost: 50, damage: '1d10 колющий', weight: 18, properties: ['Боеприпас (100/400)', 'Двуручное', 'Тяжелое'], source: 'dnd.su' },
  { id: 'longbow', name: 'Длинный лук', type: 'weapon', cost: 50, damage: '1d8 колющий', weight: 2, properties: ['Боеприпас (150/600)', 'Двуручное', 'Тяжелое'], source: 'dnd.su' },
  { id: 'net', name: 'Сеть', type: 'weapon', cost: 1, damage: '0', weight: 3, properties: ['Метательное (5/15)', 'Особое'], source: 'dnd.su' },

  // Magic Items
  { id: 'bag_of_holding', name: 'Сумка хранения', type: 'gear', cost: 500, weight: 15, description: 'Вмещает 500 фунтов, весит 15.', source: 'dnd.su' },
  { id: 'potion_healing_greater', name: 'Зелье лечения (Большое)', type: 'gear', cost: 150, weight: 0.5, properties: ['4d4+4 ХП'], source: 'dnd.su' },
  { id: 'potion_healing_superior', name: 'Зелье лечения (Отличное)', type: 'gear', cost: 500, weight: 0.5, properties: ['8d4+8 ХП'], source: 'dnd.su' },
  { id: 'weapon_plus_one', name: 'Оружие +1', type: 'weapon', cost: 500, damage: '1d8+1 магический', weight: 3, description: 'Выберите тип оружия при покупке.', source: 'dnd.su' },
  { id: 'armor_plus_one', name: 'Доспех +1', type: 'armor', cost: 1500, ac: 13, weight: 10, description: '+1 к КД любого доспеха.', source: 'dnd.su' },
  { id: 'boots_of_elvenkind', name: 'Сапоги эльфийского народа', type: 'gear', cost: 500, weight: 1, description: 'Бесшумные шаги.', source: 'dnd.su' },
  { id: 'cloak_of_protection', name: 'Плащ защиты', type: 'gear', cost: 800, weight: 3, description: '+1 КД и спасброски.', source: 'dnd.su' },

  // Gear
  { id: 'backpack', name: 'Рюкзак', type: 'gear', cost: 2, weight: 5, source: 'dnd.su' },
  { id: 'rope', name: 'Веревка пеньковая (50 фт)', type: 'gear', cost: 1, weight: 10, source: 'dnd.su' },
  { id: 'torch', name: 'Факел', type: 'gear', cost: 0.01, weight: 1, source: 'dnd.su' },
  { id: 'rations', name: 'Рационы (1 день)', type: 'gear', cost: 0.5, weight: 2, source: 'dnd.su' },
  { id: 'bedroll', name: 'Спальник', type: 'gear', cost: 1, weight: 7, source: 'dnd.su' },
  { id: 'waterskin', name: 'Бурдюк', type: 'gear', cost: 0.2, weight: 5, source: 'dnd.su' },
  { id: 'potion_healing', name: 'Зелье лечения', type: 'gear', cost: 50, weight: 0.5, properties: ['Восстанавливает 2d4+2 ХП'], source: 'dnd.su' },
  { id: 'thieves_tools', name: 'Воровские инструменты', type: 'tool', cost: 25, weight: 1, source: 'dnd.su' },
  { id: 'holy_symbol', name: 'Священный символ', type: 'gear', cost: 5, weight: 1, source: 'dnd.su' },
  { id: 'arcane_focus', name: 'Магическая фокусировка', type: 'gear', cost: 10, weight: 1, source: 'dnd.su' },
  { id: 'druidic_focus', name: 'Друидическая фокусировка', type: 'gear', cost: 1, weight: 1, source: 'dnd.su' },
  { id: 'spellbook', name: 'Книга заклинаний', type: 'gear', cost: 50, weight: 3, source: 'dnd.su' },
  
  // Packs
  { id: 'explorers_pack', name: 'Набор путешественника', type: 'gear', cost: 10, weight: 59, description: 'Рюкзак, спальник, столовый набор, трутница, 10 факелов, 10 рационов, бурдюк, 50фт веревки.', source: 'dnd.su' },
  { id: 'diplomats_pack', name: 'Набор дипломата', type: 'gear', cost: 39, weight: 46, description: 'Сундук, 2 контейнера для карт, одежда (отличная), чернила, перо, лампа, масло, бумага, благовония.', source: 'dnd.su' },
  { id: 'burglars_pack', name: 'Набор взломщика', type: 'gear', cost: 16, weight: 46, description: 'Рюкзак, шарики (1000), леска, колокольчик, свечи, ломик, молоток, шлямбуры, масло, рационы, трутница, бурдюк, веревка.', source: 'dnd.su' },
  { id: 'entertainers_pack', name: 'Набор артиста', type: 'gear', cost: 40, weight: 38, description: 'Рюкзак, спальник, костюмы (2), свечи, рационы, бурдюк, грим.', source: 'dnd.su' },
  { id: 'dungeoneers_pack', name: 'Набор исследователя подземелий', type: 'gear', cost: 12, weight: 61, description: 'Рюкзак, ломик, молоток, шлямбуры, факелы, трутница, рационы, бурдюк, веревка.', source: 'dnd.su' },
  { id: 'priests_pack', name: 'Набор священника', type: 'gear', cost: 19, weight: 24, description: 'Рюкзак, одеяло, свечи, трутница, коробка для пожертвований, благовония, облачение, рационы, бурдюк.', source: 'dnd.su' },
  { id: 'scholars_pack', name: 'Набор ученого', type: 'gear', cost: 40, weight: 10, description: 'Рюкзак, научная книга, чернила, перо, пергамент, песок, нож.', source: 'dnd.su' },
  
  // Clothes
  { id: 'clothes_common', name: 'Одежда, обычная', type: 'gear', cost: 0.5, weight: 3, source: 'dnd.su' },
  { id: 'clothes_traveler', name: 'Одежда, дорожная', type: 'gear', cost: 2, weight: 4, source: 'dnd.su' },
  { id: 'clothes_fine', name: 'Одежда, отличная', type: 'gear', cost: 15, weight: 6, source: 'dnd.su' },
];
