
import { Feat } from '../types';

export const FEATS: Feat[] = [
  // PHB
  { id: 'alert', name: 'Бдительный', description: '+5 к инициативе, нельзя застать врасплох.', source: 'dnd.su' },
  { id: 'actor', name: 'Актер', description: '+1 ХАР. Преимущество на обман/выступление.', source: 'dnd.su' },
  { id: 'athlete', name: 'Атлет', description: '+1 СИЛ/ЛОВ. Быстрое вставание, лазание без штрафа.', source: 'dnd.su' },
  { id: 'charger', name: 'Таран', description: 'Бонусная атака/толчок после рывка.', source: 'dnd.su' },
  { id: 'crossbow_expert', name: 'Эксперт арбалетов', description: 'Нет помехи в ближнем, бонусный выстрел.', source: 'dnd.su' },
  { id: 'defensive_duelist', name: 'Оборонительный боец', description: 'Реакцией +БМ к КД с фехтовальным.', source: 'dnd.su' },
  { id: 'dual_wielder', name: 'Обоюдоострый', description: '+1 КД с двумя оружиями, можно не легкие.', source: 'dnd.su' },
  { id: 'dungeon_delver', name: 'Исследователь подземелий', description: 'Бонусы к поиску ловушек и спасброскам.', source: 'dnd.su' },
  { id: 'durable', name: 'Крепкий', description: '+1 ТЕЛ. Минимум хитов при лечении.', source: 'dnd.su' },
  { id: 'elemental_adept', name: 'Адепт стихий', description: 'Игнор сопротивления выбранной стихии.', source: 'dnd.su' },
  { id: 'grappler', name: 'Борец', description: 'Преимущество на атаку по схваченным.', source: 'dnd.su' },
  { id: 'great_weapon_master', name: 'Мастер двуручного оружия', description: '-5 к атаке / +10 к урону.', source: 'dnd.su' },
  { id: 'healer', name: 'Целитель', description: 'Лечение комплектом целителя.', source: 'dnd.su' },
  { id: 'heavily_armored', name: 'Тяжелобронированный', description: '+1 СИЛ. Владение тяжелой броней.', source: 'dnd.su' },
  { id: 'heavy_armor_master', name: 'Мастер тяжелой брони', description: '+1 СИЛ. -3 урона от физ. атак.', source: 'dnd.su' },
  { id: 'inspiring_leader', name: 'Вдохновляющий лидер', description: 'Врем. ХП союзникам (Уровень + ХАР).', source: 'dnd.su' },
  { id: 'keen_mind', name: 'Иммунитет к забывчивости', description: '+1 ИНТ. Память на детали 30 дней.', source: 'dnd.su' },
  { id: 'lightly_armored', name: 'Легкобронированный', description: '+1 СИЛ/ЛОВ. Владение легкой броней.', source: 'dnd.su' },
  { id: 'linguist', name: 'Лингвист', description: '+1 ИНТ. 3 новых языка.', source: 'dnd.su' },
  { id: 'lucky', name: 'Везунчик', description: '3 удачи на переброс.', source: 'dnd.su' },
  { id: 'mage_slayer', name: 'Убийца магов', description: 'Реакция на заклинание рядом. Помеха на концентрацию врага.', source: 'dnd.su' },
  { id: 'magic_initiate', name: 'Посвященный в магию', description: '2 заговора и 1 закл. 1 круга.', source: 'dnd.su' },
  { id: 'martial_adept', name: 'Адепт боевых искусств', description: '1 кость превосходства, 2 приема.', source: 'dnd.su' },
  { id: 'medium_armor_master', name: 'Мастер средних доспехов', description: 'Нет помехи на скрытность. +3 МАКС ЛОВ к КД.', source: 'dnd.su' },
  { id: 'mobile', name: 'Подвижный', description: '+10 ск. Нет провоцированных атак после удара.', source: 'dnd.su' },
  { id: 'mounted_combatant', name: 'Верховой боец', description: 'Преимущество на атаку пеших.', source: 'dnd.su' },
  { id: 'observant', name: 'Внимательный', description: '+5 пасс. внимательность.', source: 'dnd.su' },
  { id: 'polearm_master', name: 'Мастер древкового оружия', description: 'Бонусная атака древком. Провоцированная при входе.', source: 'dnd.su' },
  { id: 'resilient', name: 'Устойчивый', description: '+1 хар. Владение спасброском.', source: 'dnd.su' },
  { id: 'ritual_caster', name: 'Ритуальный заклинатель', description: 'Книга ритуалов.', source: 'dnd.su' },
  { id: 'savage_attacker', name: 'Яростный атаки', description: 'Переброс урона оружия.', source: 'dnd.su' },
  { id: 'sentinel', name: 'Страж', description: 'Атака реакцией. Остановка врага.', source: 'dnd.su' },
  { id: 'sharpshooter', name: 'Меткий стрелок', description: '-5 к атаке / +10 к урону. Игнор укрытий.', source: 'dnd.su' },
  { id: 'shield_master', name: 'Мастер щитов', description: 'Толчок щитом. Бонус к спасброскам ЛОВ.', source: 'dnd.su' },
  { id: 'skilled', name: 'Искусный', description: '3 навыка или инструмента.', source: 'dnd.su' },
  { id: 'skulker', name: 'Скрытный', description: 'Скрытность в слабом освещении.', source: 'dnd.su' },
  { id: 'spell_sniper', name: 'Снайпер заклинаний', description: 'Удвоение дальности. Игнор укрытий.', source: 'dnd.su' },
  { id: 'tavern_brawler', name: 'Трактирный драчун', description: 'Владение импровизированным. Захват бонусом.', source: 'dnd.su' },
  { id: 'tough', name: 'Живучий', description: '+2 ХП за уровень.', source: 'dnd.su' },
  { id: 'war_caster', name: 'Боевой заклинатель', description: 'Концентрация с преимуществом. Заклинания как реакция.', source: 'dnd.su' },
  { id: 'weapon_master', name: 'Мастер оружия', description: '+1 СИЛ/ЛОВ. 4 оружия.', source: 'dnd.su' },

  // Tasha / Xanathar
  { id: 'artificer_initiate', name: 'Посвященный в изобретатели', description: 'Заговор, заклинание 1 уровня, инструменты.', source: 'dnd.su' },
  { id: 'chef', name: 'Повар', description: '+1 ТЕЛ/МДР. Готовка еды для лечения.', source: 'dnd.su' },
  { id: 'crusher', name: 'Дробитель', description: '+1 СИЛ/ТЕЛ. Отталкивание при дробящем уроне.', source: 'dnd.su' },
  { id: 'eldritch_adept', name: 'Мистический адепт', description: 'Одно воззвание колдуна.', source: 'dnd.su' },
  { id: 'fey_touched', name: 'Прикосновение фей', description: '+1 ИНТ/МДР/ХАР. Туманный шаг + 1 закл.', source: 'dnd.su' },
  { id: 'fighting_initiate', name: 'Посвященный в боевые стили', description: 'Один боевой стиль воина.', source: 'dnd.su' },
  { id: 'gunner', name: 'Стрелок', description: '+1 ЛОВ. Владение огнестрелом, нет помехи в ближнем.', source: 'dnd.su' },
  { id: 'metamagic_adept', name: 'Адепт метамагии', description: '2 очка чародейства, 2 метамагии.', source: 'dnd.su' },
  { id: 'piercer', name: 'Колющий', description: '+1 СИЛ/ЛОВ. Переброс колющего урона.', source: 'dnd.su' },
  { id: 'poisoner', name: 'Отравитель', description: 'Игнор сопр. яду, создание ядов.', source: 'dnd.su' },
  { id: 'shadow_touched', name: 'Прикосновение тени', description: '+1 ИНТ/МДР/ХАР. Невидимость + 1 закл.', source: 'dnd.su' },
  { id: 'skill_expert', name: 'Эксперт в навыках', description: '+1 хар, навык, компетентность.', source: 'dnd.su' },
  { id: 'slasher', name: 'Рубака', description: '+1 СИЛ/ЛОВ. Замедление при рубящем уроне.', source: 'dnd.su' },
  { id: 'telekinetic', name: 'Телекинетик', description: '+1 ИНТ/МДР/ХАР. Невидимая рука, толчок.', source: 'dnd.su' },
  { id: 'telepathic', name: 'Телепат', description: '+1 ИНТ/МДР/ХАР. Обнаружение мыслей, телепатия.', source: 'dnd.su' },

  // Fizban
  { id: 'gift_chromatic', name: 'Дар хроматического дракона', description: 'Вливание стихии, сопротивление стихии.', source: 'dnd.su' },
  { id: 'gift_gem', name: 'Дар драгоценного дракона', description: '+1 ИНТ/МДР/ХАР. Телекинетический ответ.', source: 'dnd.su' },
  { id: 'gift_metallic', name: 'Дар металлического дракона', description: 'Лечение ран, защитные крылья.', source: 'dnd.su' },

  // Homebrew Feats
  { id: 'hb-alchemist-adept', name: 'Алхимик-любитель (HB)', description: 'Создание зелий за половину стоимости, +1 ИНТ.', source: 'homebrew' },
  { id: 'hb-shield-basher', name: 'Удар щитом (HB)', description: 'Атака щитом как бонусное действие (1d4 + СИЛ).', source: 'homebrew' },
  { id: 'hb-thrown-master', name: 'Мастер метания (HB)', description: 'Дальность метательного оружия удвоена, возврат оружия.', source: 'homebrew' },
  { id: 'hb-wrestler', name: 'Борец (HB)', description: 'Преимущество на захват, урон при захвате 1d4.', source: 'homebrew' },
  { id: 'hb-tactician', name: 'Тактик (HB)', description: '+1 ИНТ. Можно менять инициативу с союзником.', source: 'homebrew' },
  { id: 'hb-blood-magic', name: 'Магия крови (HB)', description: 'Жертвуете хиты для усиления заклинаний.', source: 'homebrew' },
  { id: 'hb-chronomancer', name: 'Мастер времени (HB)', description: 'Может замедлить одного врага или ускорить союзника.', source: 'homebrew' },
  { id: 'hb-master-disguise', name: 'Мастер маскировки (HB)', description: 'Автоматически проходите проверки Обмана при маскировке.', source: 'homebrew' }
];
