
import { ClassType, Ability } from '../types';

export const CLASSES: ClassType[] = [
  // --- OFFICIAL ---
  { id: 'artificer', name: 'Изобретатель', description: 'Мастер отпирания магии в обычных предметах.', hitDie: 8, primaryAbility: [Ability.INT], saves: [Ability.CON, Ability.INT], spellcastingAbility: Ability.INT, features: ['Магическое ремесленничество', 'Инфузии предметов', 'Владение инструментами', 'Верный конструкт'], startingEquipment: ['light_crossbow', 'scale_mail', 'thieves_tools', 'dungeoneers_pack'], source: 'dnd.su' },
  { id: 'barbarian', name: 'Варвар', description: 'Свирепый воин, использующий ярость в битве.', hitDie: 12, primaryAbility: [Ability.STR], saves: [Ability.STR, Ability.CON], features: ['Ярость', 'Защита без доспехов', 'Безрассудная атака', 'Чувство опасности', 'Путь примитивной магии'], startingEquipment: ['greataxe', 'handaxe', 'handaxe', 'explorers_pack', 'javelin', 'javelin', 'javelin', 'javelin'], source: 'dnd.su' },
  { id: 'bard', name: 'Бард', description: 'Вдохновляющий маг, чья сила исходит из музыки.', hitDie: 8, primaryAbility: [Ability.CHA], saves: [Ability.DEX, Ability.CHA], spellcastingAbility: Ability.CHA, features: ['Магия', 'Бардовское вдохновение', 'Мастер на все руки', 'Песнь отдыха', 'Коллегия бардов', 'Экспертиза'], startingEquipment: ['rapier', 'diplomats_pack', 'leather_armor', 'dagger'], source: 'dnd.su' },
  { id: 'cleric', name: 'Жрец', description: 'Священнический чемпион, владеющий божественной магией.', hitDie: 8, primaryAbility: [Ability.WIS], saves: [Ability.WIS, Ability.CHA], spellcastingAbility: Ability.WIS, features: ['Магия', 'Божественный домен', 'Божественный канал', 'Изгнание нежити'], startingEquipment: ['mace', 'scale_mail', 'shield', 'priests_pack', 'holy_symbol'], source: 'dnd.su' },
  { id: 'druid', name: 'Друид', description: 'Жрец Старой Веры, владеющий силами природы.', hitDie: 8, primaryAbility: [Ability.WIS], saves: [Ability.INT, Ability.WIS], spellcastingAbility: Ability.WIS, features: ['Магия', 'Друидический язык', 'Дикий облик', 'Круг друидов'], startingEquipment: ['scimitar', 'leather_armor', 'explorers_pack', 'druidic_focus', 'shield'], source: 'dnd.su' },
  { id: 'fighter', name: 'Воин', description: 'Мастер боевых искусств, владеющий разнообразным оружием.', hitDie: 10, primaryAbility: [Ability.STR, Ability.DEX], saves: [Ability.STR, Ability.CON], features: ['Боевой стиль', 'Второе дыхание', 'Всплеск действий', 'Воинский архетип', 'Дополнительная атака'], startingEquipment: ['chain_mail', 'longsword', 'shield', 'dungeoneers_pack', 'crossbow_light'], source: 'dnd.su' },
  { id: 'monk', name: 'Монах', description: 'Мастер боевых искусств, использующий энергию тела.', hitDie: 8, primaryAbility: [Ability.DEX, Ability.WIS], saves: [Ability.STR, Ability.DEX], features: ['Защита без доспехов', 'Боевые искусства', 'Ци', 'Шквал ударов', 'Терпеливая оборона', 'Поступь ветра', 'Отражение снарядов'], startingEquipment: ['shortsword', 'dungeoneers_pack', 'dart', 'dart', 'dart', 'dart', 'dart', 'dart', 'dart', 'dart', 'dart', 'dart'], source: 'dnd.su' },
  { id: 'paladin', name: 'Паладин', description: 'Святой воин, связанный священной клятвой.', hitDie: 10, primaryAbility: [Ability.STR, Ability.CHA], saves: [Ability.WIS, Ability.CHA], spellcastingAbility: Ability.CHA, features: ['Божественное чувство', 'Наложение рук', 'Боевой стиль', 'Магия', 'Божественная кара', 'Священная клятва'], startingEquipment: ['longsword', 'shield', 'chain_mail', 'holy_symbol', 'explorers_pack', 'javelin', 'javelin', 'javelin', 'javelin', 'javelin'], source: 'dnd.su' },
  { id: 'ranger', name: 'Следопыт', description: 'Воин, использующий боевые навыки и магию природы.', hitDie: 10, primaryAbility: [Ability.DEX, Ability.WIS], saves: [Ability.STR, Ability.DEX], spellcastingAbility: Ability.WIS, features: ['Избранный враг', 'Исследователь природы', 'Боевой стиль', 'Магия', 'Архетип следопыта', 'Первозданная осведомленность'], startingEquipment: ['scale_mail', 'shortsword', 'shortsword', 'longbow', 'explorers_pack'], source: 'dnd.su' },
  { id: 'rogue', name: 'Плут', description: 'Плут использует скрытность и хитрость.', hitDie: 8, primaryAbility: [Ability.DEX], saves: [Ability.DEX, Ability.INT], features: ['Экспертиза', 'Скрытая атака', 'Воровской жаргон', 'Хитрое действие', 'Плутовской архетип', 'Невероятное уклонение'], startingEquipment: ['rapier', 'shortbow', 'leather_armor', 'dagger', 'dagger', 'thieves_tools', 'burglars_pack'], source: 'dnd.su' },
  { id: 'sorcerer', name: 'Чародей', description: 'Заклинатель, черпающий магию из врожденного дара.', hitDie: 6, primaryAbility: [Ability.CHA], saves: [Ability.CON, Ability.CHA], spellcastingAbility: Ability.CHA, features: ['Магия', 'Происхождение чародея', 'Источник магии', 'Метамагия'], startingEquipment: ['crossbow_light', 'arcane_focus', 'dungeoneers_pack', 'dagger', 'dagger'], source: 'dnd.su' },
  { id: 'warlock', name: 'Колдун', description: 'Заклинатель, получивший магию от иномировой сущности.', hitDie: 8, primaryAbility: [Ability.CHA], saves: [Ability.WIS, Ability.CHA], spellcastingAbility: Ability.CHA, features: ['Магия пакта', 'Потусторонний покровитель', 'Мистические воззвания', 'Предмет договора'], startingEquipment: ['crossbow_light', 'arcane_focus', 'scholars_pack', 'leather_armor', 'dagger', 'dagger', 'quarterstaff'], source: 'dnd.su' },
  { id: 'wizard', name: 'Волшебник', description: 'Ученый маг, способный манипулировать структурой реальности.', hitDie: 6, primaryAbility: [Ability.INT], saves: [Ability.INT, Ability.WIS], spellcastingAbility: Ability.INT, features: ['Магия', 'Магическое восстановление', 'Магическая традиция', 'Книга заклинаний'], startingEquipment: ['quarterstaff', 'arcane_focus', 'scholars_pack', 'spellbook'], source: 'dnd.su' },
  
  // --- SIDEKICKS ---
  { id: 'warrior_sidekick', name: 'Напарник: Боец', description: 'Боевой напарник.', hitDie: 10, primaryAbility: [Ability.STR], saves: [Ability.STR, Ability.CON], features: ['Боевые стили'], startingEquipment: ['chain_mail', 'longsword', 'shield'], source: 'dnd.su' },
  { id: 'spellcaster_sidekick', name: 'Напарник: Заклинатель', description: 'Магический напарник.', hitDie: 6, primaryAbility: [Ability.INT], saves: [Ability.INT, Ability.WIS], spellcastingAbility: Ability.INT, features: ['Магия напарника'], startingEquipment: ['quarterstaff', 'leather_armor'], source: 'dnd.su' },
  { id: 'expert_sidekick', name: 'Напарник: Эксперт', description: 'Ловкий напарник.', hitDie: 8, primaryAbility: [Ability.DEX], saves: [Ability.DEX, Ability.INT], features: ['Экспертные навыки'], startingEquipment: ['shortsword', 'leather_armor', 'thieves_tools'], source: 'dnd.su' },

  // --- HOMEBREW ---
  { id: 'alchemist-hb', name: 'Алхимик', description: 'Мастер зелий и экспериментов.', hitDie: 8, primaryAbility: [Ability.INT], saves: [Ability.INT, Ability.CON], features: ['Алхимические снаряды', 'Алхимический путь'], startingEquipment: ['crossbow_light', 'leather_armor', 'alchemists_supplies'], source: 'homebrew' },
  { id: 'alternate-fighter', name: 'Альтернативный воин', description: 'Упрощённый и сбалансированный вариант воина.', hitDie: 10, primaryAbility: [Ability.STR, Ability.DEX], saves: [Ability.STR, Ability.CON], features: ['Упрощённые способности', 'Тактический выбор'], startingEquipment: ['chain_mail', 'longsword'], source: 'homebrew' },
  { id: 'alternate-monk', name: 'Альтернативный монах', description: 'Модернизированный монах с новыми путями.', hitDie: 8, primaryAbility: [Ability.DEX, Ability.WIS], saves: [Ability.STR, Ability.DEX], features: ['Новые стили ки', 'Улучшенный поток действий'], startingEquipment: ['shortsword'], source: 'homebrew' },
  { id: 'warlord', name: 'Военачальник', description: 'Лидер отряда, усиливающий союзников.', hitDie: 10, primaryAbility: [Ability.CHA], saves: [Ability.WIS, Ability.CHA], features: ['Командирская аура', 'Тактический приказ'], startingEquipment: ['chain_mail', 'longsword', 'shield'], source: 'homebrew' },
  { id: 'jaeger', name: 'Егерь', description: 'Охотник на сверхъестественное.', hitDie: 10, primaryAbility: [Ability.DEX, Ability.STR], saves: [Ability.DEX, Ability.WIS], features: ['Следопыт', 'Охотничий знак'], startingEquipment: ['scale_mail', 'greatsword'], source: 'homebrew' },
  { id: 'stargazer', name: 'Звездочёт', description: 'Астролог, черпающий силу из звёзд.', hitDie: 8, primaryAbility: [Ability.INT], saves: [Ability.INT, Ability.WIS], features: ['Звёздные предсказания', 'Созвездия'], startingEquipment: ['leather_armor', 'quarterstaff'], source: 'homebrew' },
  { id: 'blood_hunter', name: 'Кровавый Охотник', description: 'Воин, использующий магию крови для охоты на чудовищ.', hitDie: 10, primaryAbility: [Ability.STR, Ability.DEX, Ability.INT], saves: [Ability.DEX, Ability.INT], features: ['Проклятие крови', 'Багровый ритуал', 'Клеймо наказания'], startingEquipment: ['longsword', 'leather_armor', 'crossbow_light', 'explorers_pack'], source: 'homebrew' },
  { id: 'magus', name: 'Магус', description: 'Полу-воин, полу-маг, сливающий магию с оружием.', hitDie: 10, primaryAbility: [Ability.INT], saves: [Ability.INT, Ability.CON], features: ['Магическое оружие', 'Арканное сосредоточение'], startingEquipment: ['scale_mail', 'longsword'], source: 'homebrew' },
  { id: 'mystic', name: 'Мистик', description: 'Псионический класс, заменяющий магию на силу разума.', hitDie: 8, primaryAbility: [Ability.INT], saves: [Ability.INT, Ability.WIS], spellcastingAbility: Ability.INT, features: ['Псионика', 'Пси-таланты', 'Дисциплины'], startingEquipment: ['spear', 'leather_armor', 'scholars_pack'], source: 'homebrew' },
  { id: 'lingering-soul', name: 'Неупокоенная душа', description: 'Существо, вернувшееся из мёртвых.', hitDie: 8, primaryAbility: [Ability.CHA], saves: [Ability.WIS, Ability.CHA], features: ['Воскрешение', 'Аура страха'], startingEquipment: ['simple_weapon'], source: 'homebrew' },
  { id: 'savant', name: 'Савант', description: 'Гений с уникальными научными способностями.', hitDie: 6, primaryAbility: [Ability.INT], saves: [Ability.INT, Ability.CON], features: ['Научные формулы', 'Технологии'], startingEquipment: ['leather_armor', 'dagger'], source: 'homebrew' },
  { id: 'runekeeper', name: 'Хранитель рун', description: 'Мастер древних рун и символической магии.', hitDie: 8, primaryAbility: [Ability.INT], saves: [Ability.INT, Ability.WIS], features: ['Руническая магия', 'Рунический щит'], startingEquipment: ['scale_mail', 'warhammer'], source: 'homebrew' },
  { id: 'shaman', name: 'Шаман', description: 'Посредник между миром живых и духов.', hitDie: 8, primaryAbility: [Ability.WIS], saves: [Ability.WIS, Ability.CHA], features: ['Призыв духов', 'Духовная связь'], startingEquipment: ['leather_armor', 'quarterstaff'], source: 'homebrew' },
  { id: 'gunslinger', name: 'Стрелок', description: 'Мастер огнестрельного оружия.', hitDie: 10, primaryAbility: [Ability.DEX], saves: [Ability.DEX, Ability.INT], features: ['Владение огнестрелом', 'Очки ухарства'], startingEquipment: ['leather_armor', 'thieves_tools'], source: 'homebrew' }
];
